### ISSUE TITLE
Instructions for noobs

### ISSUE THREAD

**Issue by Xelendor1** [Yubico/yubihsm-shell#181]
hello, 

one thing to note, after the "make" command, you need "make install", I was googling for hours and it was a super simple fix.  Might be good to add it to the documentation for the other noobs out there.  

This dependancy was also required(needed to specify the dev version)
sudo apt install libpcsclite-dev

also this one for the Rockpi
help2man

cheers and thanks for the build! got it working

**Comment by aveenismail** [comment]
Thank you for opening an issue.

I made a pull  request to add libpcsclite-dev. help2man is already listed as a dependency. It's marked as optional since it's only used to generate man pages and one can skip generating man pages by building with the option WITHOUT_MANPAGES turned on.

"make install" is not actually required for building. One can fully build, test and use the software from the location cmake is configured to build it in (by default: current directory). "make install" practically just copies the binaries to a destination. In this case, the destination is set in the CMAKE_INSTALL_PREFIX option (by default: "/usr/local" or "C:/Program Files/${PROJECT_NAME}"). As this could put the binaries in PATH and often requires admin privileges, it may not be desirable to automatically run "make install" after every build

**Comment by Xelendor1** [comment]
Hello,

Thank you for the response!
How do I test the binaries in the build director?  something like
->./yubisim-connector connect  ?

thank you,

Mack

**Comment by aveenismail** [comment]
Hi Mack

It depends on what it is you're trying to do. The most straight forward way to communicate with the YubiHSM is to use the yubihsm-shell command line tool. You can find it in build/src directory. If you're using yubihsm_pkcs11.so/dylib, that will be located in build/pkcs11 directory. This assumes that you are running on a Linux or Mac system. The location will be a little different if you're running on a Windows machine, but they will still be inside the build directory.

If something is not clear, don't hesitate to ask

Aveen

**Comment by kobrien** [comment]
if anybody else is having trouble installing libcurl, this package worked for me `4-openssl-dev` (on ubuntu 20.04)

**Comment by Xelendor1** [comment]
is there binaries for the yubihsm-connector?  I don't see them in list or in the bin folder.  Anyway to open the connector on ARM?

**Comment by aveenismail** [comment]
Hi Mack,

The yubihsm-connector binary is available through the yubihsm-sdk release package available from https://developers.yubico.com/YubiHSM2/Releases/

The binaries built for ARM architecture is https://developers.yubico.com/YubiHSM2/Releases/yubihsm2-sdk-2021-04-darwin-arm64.pkg

The yubihsm-sdk release package contains the binaries for yubihsm-shell, yubihsm-connector and yubihsm-setup (and yubihsm-ksp for Windows). Using the .pkg installer will install those binaries in the default location, which will put them on PATH

**Comment by aveenismail** [comment]
Sorry. I may have misunderstood what platform you're running on. We don't have binaries built specifically for ARM architecture with Linux, but there shouldn't be problem building it from source. Go to yubihsm-connector source directory and run `make` (See https://developers.yubico.com/yubihsm-connector/ for dependencies). The executable will then be available in `yubihsm-connector/bin/yubihsm-connecor`. Make sure to run the connector with the right permissions (see https://developers.yubico.com/YubiHSM2/Component_Reference/yubihsm-connector/)

**Comment by qpernil** [comment]
You may also cross-compile as shown in the README for yubihsm-connector. This will require installing cross build tools on the host machine.

**Comment by qpernil** [comment]
Closing this now as it is presumably solved. Please feel free to open another issue if needed.
