### ISSUE TITLE
Alternative to the yubihsm-shell wrap/encrypt and unwrap/decrypt

### ISSUE THREAD

**Issue by cnburke** [Yubico/yubihsm-shell#189]
Per the "Known Issues" page on developers.yubico.com, I'm aware that the encryption and decryption commands are "unimplemented". I'm currently looking for a solution to generate a object on the YubiHSM2, export it under wrap, and decrypt it locally on my machine. We have current need to generate an object (an HMAC, for example), export it, and send it to a manufacturer for production. 

We have successfully accomplished generating a wrap key, importing a wrap key, and exporting an object under wrap with a stored wrap key. 

We'd like to just use the wrap key (aes ccm key) that we generated in our linux environment to decrypt the exported wrapped object. We currently do not have a way to do this without the decrypt/unwrap data commands being unimplemented in the yubihsm-shell. 

Please provide guidance. We appreciate your help in advance! 

Operating system: Ubuntu 18.04
Using release 2021.08 (from a few days ago), have also used the 2021.04 in our efforts over the past few days.

**Comment by qpernil** [comment]
Hope I'm not stating the obvious, but to do something like that you'd need to have the same wrap key in the HSM, hence you need to import the wrap key, since you typically can't export it (except maybe under another wrap key). Also, a key must have the capability exportable-under-wrap to be exportable at all. Then you can export keys to that wrap key, and can then decrypt them in you external environment, in theory. We do not currently provide a tool to do this, but it is being considered.

**Comment by qpernil** [comment]
I'd also venture to say that if they key is exported and unwrapped to cleartext it might as well be generated elsewhere and imported into the hsm instead.

**Comment by cnburke** [comment]
Yep - I hear what you're saying. We wanted to use the FIPS version of the HSM for generating the keys, due to some regulatory compliance for generating all keys on FIPS compliant devices. 

That said - I ended up creating a "yubihsm-unwrap" application based off of the yubihsm-wrap code for exporting and decrypting the generated key using a wrap key generated external to the device. That was a pain...but it works now :)

**Comment by qpernil** [comment]
If you'd like to contribute, feel free... As I said this has been considered to be added.
