### ISSUE TITLE
can't import certificate on YubiHSM 2

### ISSUE THREAD

**Issue by hphp93** [Yubico/yubihsm-shell#213]
I am trying to import a certificate from my Java code to the YubiHSM 2 using ks.setEntry, but I am getting the following exception: **trusted certificates may only be set by token initialization application**

The logfile doesn't give me any information, it just stops at a certain point.
Does anyone know what causes this?

**Comment by a-dma** [comment]
Hi, I assume you're using the PKCS#11 module? If so it would be helpful to enable debug messages in the module's configuration file. You can set a specific destination for logging.

Generally speaking, make sure that the Authentication key you're using has the necessary capabilities for the operation that you're trying to perform, and that you application calls the login function to establish a session with the YubiHSM.

**Comment by qpernil** [comment]
The error message seems to indicate you are trying to set the CKA_TRUSTED attribute for the certificate, which apparently isn't allowed by Java. You could also set YUBIHSM_PKCS11_DBG and YUBIHSM_PKCS11_DINOUT environment variables to 1 to get so logging from yubihsm_pkcs11.

**Comment by hphp93** [comment]
> Hi, I assume you're using the PKCS#11 module? If so it would be helpful to enable debug messages in the module's configuration file. You can set a specific destination for logging.
> 
> Generally speaking, make sure that the Authentication key you're using has the necessary capabilities for the operation that you're trying to perform, and that you application calls the login function to establish a session with the YubiHSM.

Hey, I didn't include the logfile because I didn't really find any useful information but here it is: https://pastebin.com/z8aajze2.
About the capabilities, I don't see any specific capability for importing a certificate aside from put-opaque which is enabled.

Exception is as said before: trusted certificates may only be set by token initialization application.

Right now I am sending/obtaining keys and then performing the cryptographic actions in the Java code. But then what is the point of having the YubiHSM 2.

**Comment by hphp93** [comment]
> The error message seems to indicate you are trying to set the CKA_TRUSTED attribute for the certificate, which apparently isn't allowed by Java. You could also set YUBIHSM_PKCS11_DBG and YUBIHSM_PKCS11_DINOUT environment variables to 1 to get some logging from yubihsm_pkcs11.

Do you have any source on why it isn't allowed by Java?

**Comment by qpernil** [comment]
This document seems to indicate it: https://docs.oracle.com/en/java/javase/11/security/pkcs11-reference-guide1.html
See SunPKCS11 Provider KeyStore Requirements, the section called Write Access. I based my initial observation on the error message, plus the fact that there is no error in the yubihsm_pkcs11 log. This hints at the Java side disallowing it before calling pkcs11.

**Comment by qpernil** [comment]
I would also add that storing trusted certificates on the device is not that relevant as those are likely certificates without private keys (ca certificates, or possibly intermediate certificates). What makes more sense is to store the certificates for which you have private keys on the HSM as well.

**Comment by hphp93** [comment]
> I would also add that storing trusted certificates on the device is not that relevant as those are likely certificates without private keys (ca certificates, or possibly intermediate certificates). What makes more sense is to store the certificates for which you have private keys on the HSM as well. The meaning of trusted should probably be seen as certificates you trust as roots of certificate chains for other people (or web servers etc), not necessarily your own keys / certificates.

I was using a self signed certificate and still got the error message about trusted certificates. I have never used a trusted certificate. That's why I'm confused.

**Comment by qpernil** [comment]
I read some more docs about Java's requirements on PKCS#11 modules and it seems to be able to use certificates with CKA_TRUSTED already set when building it's internal keystore, in which case they are used to build certificate chains. When the keystore wants to write to the PKCS#11 module it looks a little more unclear. They seem to be saying that it is not allowed to write trusted certificates to the module from normal applikations, only from card management applications. If that means it can only be done 'some other way', not using Java, or if it only means you have to log in as SO to do it, is very unclear.
But the point remains that it seems Java is not trying to write them in your test, so the problem is likely not in yubihsm_pkcs11. I can't rule it out altogether, but at least not directly as there were no logs to that effect. Indirectly I suppose it's possible that something we return from the module makes it behave like this, but that is just speculation.
My advice would be to experiment a little with you Java application and note what it does with the pkcs11 module, by turning on full debugging. You can set environment variables that will be picked up by yubihsm-pkcs11, or use the config file.

**Comment by hphp93** [comment]
I came to the conclusion that pkcs#11 doesn't allow it due to security reasons. I read somewhere that it is done to counter for example insider threats, unfortunately I don't have the source to this anymore.

"_The CKA_TRUSTED attribute cannot be set to true by an application. It must be set by a token initialization application or by the token’s SO. Trusted certificates cannot be modified._"

I guess that in this case the token initialization application would be the YubiShell and the SO (Security Officer) would be me.

**Comment by qpernil** [comment]
From a practical standpoint the pkcs11 library doesn't seem to be called, and that decision is taken by the Java PKCS11 wrapper layer, it seems. Hence there isn't anything we can do in our code. Also, yubihsm_pkcs11 doesn't support 'SO' users. This is because the HSM provides the user with a much more nuanced range of capabilites based on what the authentication key gives you. This is set up when that key is created, and you 'inherit' those rights when you log in. You can also create new authentication keys with less or equal capabilities if you want a user to have limited use of the HSM for example. This complexity can't really be mapped to SO or normal USER, hence all logins are USER type in the PKCS11 layer. Maybe we should allow SO type logins as well, in the exackt same way, just to enable scenarios where a client app you didn't write yourself has limitations.

**Comment by qpernil** [comment]
Im closing this issue now as it has been inactive for a while. Don't hesitate to open a new issue if needed.
