### ISSUE TITLE
How to connect HTTPS to YubiHSM2 using libyubihsm.dll

### ISSUE THREAD

**Issue by PeaceTime1** [Yubico/yubihsm-shell#244]
> `$ yubihsm-connector -d --cert=cert.pem --key=key.pem`

> `$ yubihsm-shell --connector=https://localhost:12345 --cacert=cert.pem`

How can I do the same function as shown for the yubihsm-shell with libyubihsm.dll?

_Originally posted by @mouse07410 in https://github.com/Yubico/yubihsm-shell/issues/5#issuecomment-442843167_

**Comment by qpernil** [comment]
The following is what the --cacert option does

      if (yh_set_connector_option(ctx->connector, YH_CONNECTOR_HTTPS_CA,
                                  ctx->cacert) != YHR_SUCCESS) {
        fprintf(stderr, "Failed setting HTTPS CA\n");
        break;
      }

**Comment by PeaceTime1** [comment]
I get YHR_CONNECTOR_ERROR  -29 on the call to yh_set_connector_option

Code running that calls libyubihsm:
yrc = yh_init32();
yrc = yh_init_connector32("https://100.5.70.160:44625", &connector);
yrc = yh_set_connector_option(connector, YH_CONNECTOR_HTTPS_CA, "Yubicert.pem");
yrc = yh_connect32(connector, 0);


connector started as follows (batch file)
start cmd.exe /k "c:\schedule\yubihsm-connector.exe -d -l 100.5.70.160:44625 -c c:\schedule\test.yaml"


test.yaml has the following:
# Certificate (X.509)
cert: "c:\\schedule\\Yubicert.pem"
#
# Certificate key
key: "c:\\schedule\\Yubikey.pem"
#

Yubicert.pem and Yubikey.pem were created as follows:

using Git Bash

$ openssl req -nodes -x509 -newkey rsa:4096 -keyout Yubikey.pem -out Yubicert.pem -sha256 -days 365 -subj '//CN=localhost'

**Comment by qpernil** [comment]
I see you are on Windows, didn't catch that at first. Im afraid we haven't implemented those options on Windows. But we are using WinHttp, so if you install the CA certificate as trusted in Windows so that for example the edge browser can connect without warnings, then it should work in the http backend as well.

**Comment by qpernil** [comment]
To clarify: We added support for this through an external pull request, which only dealt with curl. We elected to include it because it was useful on Linux and MacOS, even though it doesn't work on Windows (since there we use WinHttp, not curl). This is in order to minimize dependencies. Of course, it might be possible to build a curl http backend on Windows, but it is untested.

**Comment by qpernil** [comment]
Closing this now for lack of activity. Don't hesitate to post again if needed.
