### ISSUE TITLE
How do I sign a raw digest, using an RSA4096 private key

### ISSUE THREAD

**Issue by TonyDevC1** [Yubico/yubihsm-shell#245]
Hi, I'm just starting out developing my first application using a YubiHSM2 written in C (under Windows), and I am practicing my workflow inside the yubihsm-shell.
I need to be able to generate an RSA4096 private key, and then extract a public key from it. I then need to be able to able to sign digests that I will have already created in my own code, and so will need to perform on the YubiHSM2, the equivalent to:

    openssl rsautl -raw -sign -in digest.hash -out digest.sig -inkey private.key

Whereby digest.hash is a 512 byte raw binary hash created by my software. BTW, the hash I create will either be SHA-256 or BLAKE2S with appropriate padding. I can generate a key with the following shell command:

    generate asymmetric 0 2 Test_Key 1 sign-pkcs rsa4096

However, if I try to sign a digest with it, using:

    sign pkcs1v1_5 0 0x0002 rsa4096 digest.hash

I get the error "Invalid hash algorithm". I can see from the documentation that the sign pkcs1v1_5 supports only the following algorithms: SHA-1, SHA-256, SHA-384 and SHA-512. So now I'm starting to doubt whether what I am trying to do is even possible on the YubiHSM2.

Any help with this issue will be much appreciated.
Regards,
Tony.

**Comment by TonyDevC1** [comment]
Hi, and thanks for the feedback and the useful tips regarding the yubihsm-shell usage. I did try the rsa-pkcs1-sha256 algorithm, and that did indeed work.

I am interested to know, if I sign a hash digest with rsa-pkcs1-sha256 specified as the algorithm, will the YubiHSM care if the hash was created using SHA-256 or BLAKE2S? We need to be able to use BLAKE2S hashes as well. I ask, because I am curious as to why the RSA signing needs to know which algorithm was used for creating the hash digest, and therefore understand the impact of this parameter on the signature.

Again many thanks!
Tony.

**Comment by a-dma** [comment]
this mostly comes from PKCS#1 (and its iterations, see https://datatracker.ietf.org/doc/html/rfc8017 for example).

When you sign data with RSA, the message has to be encoded in a so called `DigestInfo` i.e. a padded version of the hash that includes the OID of the hashing algorithm so that whoever tries to verify the signature knows how to recreate the right hash starting from the message. There is no specification for BLAKE2s in PKCS#1 (see section A.2 from the link above), which means that you can't generate signatures using that hash algorithm with the YubiHSM, and even if you could you would have a hard time finding anything that can verify such a signature out of the box.

That said, I don't know exactly what your requirements are but what you can do is sign a digest of your data instead of the data itself, and _that_ digest can be computed with anything that you want. Of course you'll have to do something similar during verification and it may not fit your requirements in general.

**Comment by TonyDevC1** [comment]
Hi, that is most useful. I should have made it clearer before. Our own software will be responsible for verification, and so all we need to verify from the resulting signature, is the RSA encryption using the public key. We'll check the digest in our own code. Our software will create the hash and padding, to create a 512 byte digest. I guess I just need to know that if we use the library function yh_util_sign_pkcs1v1_5() to perform the equivalent to the shell command:

    sign pkcs1v1_5 0 0x0002 rsa-pkcs1-sha256 digest.hash

that we would get a signature equivalent to if we used:

    openssl rsautl -raw -sign -in digest.hash -out digest.sig -inkey private.key

Obviously assuming the private keys were the same. Essentially we just need to know that the verification of the RSA encryption would work given a public key.

Many Thanks.
Tony.

**Comment by a-dma** [comment]
not quite. The YubiHSM will check the DigestInfo and insert it for you if it is missing, so calling `yh_util_sign_pkcs1v1_5` is not the same as using `-raw` in OpenSSL. There is no way to sign raw data with a YubiHSM. You have to use either PKCS#1v1.5 or PSS (for RSA of course).

If you control the verification side you have some amount of flexibility, but I would encourage you to stick with default schemes and behavior.

**Comment by a-dma** [comment]
the DigestInfo is the DER encoding of the hash OID followed by the hash itself. It is more than four bytes.

For the rest, yes you are correct, with some minor adjustments. The padding is not part of the message sent to the device, it is done by the device. If the DigestInfo doesn't encode a supported hash algorithm i.e. if it has an incorrect length or unsupported OID, then an error will be produced. No hashing happens in the device.

**Comment by TonyDevC1** [comment]
Finally, thank you for clarifying and answering my questions!

Regards,
Tony.

**Comment by a-dma** [comment]
No worries, glad it helped.
