### ISSUE TITLE
PKCS11 Find Object behaviour broken in release 2.4.0 when CKA_ID < 256

### ISSUE THREAD

**Issue by driseley** [Yubico/yubihsm-shell#335]
With the recent upgrade to yubihsm-shell 2.4.0, we have found that the behaviour of the pkcs11 `C_FindObjectsInit` function has been broken (in our environment we have [XCA](https://github.com/chris2511/xca/) integrated with the YubiHSM2).

I have created a reproducer here: https://github.com/driseley/yubihsm-pkcs11-test

The yubihsm setup is to create 2 asymmetric keys, one with an ID of 200 ( which can be represented with a single byte ) and the other with a ID of 65000 ( which requires 2 bytes to represent the id)

In summary - when searching for objects using the `CKA_ID` attribute the behaviour has changed between 2.3.2 and 2.4.0 as follows:

* If the value of the id can be represented in single byte (ie < 256) and is defined as uint8_t - 2.3.2 finds the public key, 2.4.0 does not (FAIL)
* If the value of the id can be represented in single byte (ie < 256) and is defined as uint16_t - 2.3.2 finds the public key, 2.4.0 also finds the key (PASS)
* If the value of the id can be represented in single byte (ie < 256) and is defined as uint32_t - 2.3.2 finds both keys and 2.4.0 finds neither (FAIL?)
* If the value of the id must be represented in two bytes (ie >= 256 && < 65536) and is defined as uint16_t - 2.3.2 finds the public key, 2.4.0 also finds the key (PASS)
* If the value of the id must be represented in two byte (ie >= 256 && < 65536) and is defined as uint32_t - 2.3.2 finds both keys and 2.4.0 finds neither (FAIL?)

(I'm not sure if passing the `CKA_ID` as a uint32_t  is supported - but the behaviour has changed between the releases - and neither appears correct to me)

The net effect of this is that XCA when using the 2.4.0 yubihsm pkcs11 library cannot match a key when attempting to sign if the key id is < 256

From some debugging I believe the issue is in the `match_meta_attributes` function: 
https://github.com/Yubico/yubihsm-shell/blob/1dfc3ffb7ff532fd77dc08530a03be528a7d51d4/pkcs11/util_pkcs11.c#L5127-L5145
I don't think attribute comparison is taking account of the possible different types that could be passed into the search

**Comment by qpernil** [comment]
According to the pkcs#11 specification CKA_ID is a byte array, i.e. it is simply seen as a certain number of bytes, and comparison of two different CKA_ID values is then a simple comparison byte by byte. Different length byte arrays are always unequal. According to the spec CKA_ID has only one function, to link different objects together when they are related, such as private key - public key - certificate for the same key. Using a uint16 or uint32 as the value for CKA_ID has two problems -  first the byte order of the client machine will cause the value to be stored either big endian or little endian, which would not work if the key was created and then used on different machines where the byte order was different. Secondly, the expectation that '5' encoded as 00 00 00 05 should match the encoding as 00 05 is not valid.

**Comment by qpernil** [comment]
Having said that - yubihsm_pkcs11 will in fact parse the CKA_ID as a 16 bit big-endian integer if the value is 2 bytes in length, and use this as the actual object id on the device when creating or generating keys. If CKA_ID is not two bytes long then it will use a random object id for new objects, and store the CKA_ID byte array as metadata (the metadata handling is purely done in yubihsm_pkcs11 and is note used in any other components). Since objects without metadata are handled as if they had the 16 bit actual object id in big endian format as CKA_ID we ensure the same CKA_ID as was set is always returned (if the new version is used. The old version always interpreted the given CKA_ID as a 16 bit big-endian integer)

**Comment by qpernil** [comment]
So if you need compatibility with other components, or just wish to avoid creating the extra metadata objects in the YubiHSM, use two byte CKA_ID values. The same is true if an object is created by other components, which would not create the metadata. The encoding should be big-endian. So, to search for object 0x1234 you need a CKA_ID such as 
uint8_t foo[] = {0x12, 0x34};

**Comment by driseley** [comment]
@qpernil - Many thanks for your responses.  

I think I now understand better what is going on in XCA.  It appears to be loading the  CKA_ID and converting it into an OpenSSL BIGNUM for internal storage.  When it then uses the id to locate the key again, it converts it into the shortest form of byte array (with big-endian encoding) that it can represent it in, hence why it fails for CKA_ID that can be represented as as single byte (ie. it does not internally persist the length of the CKA_ID attribute). 

Our problem is that we have existing keys with single byte CKA_ID values, so I need to make this work

However, from my tests the behaviour of the yubihsm pkcs11 lib did change between 2.3.2 and 2.4.0 - are you saying that the 2.4.0 behaviour is the correct one (and that the 2.3.2 behaviour was in fact a bug)?  

If so I will see if I can patch XCA to match the 2.4.0 implementation (for our purposes - I'll try and force the search to use 2 bytes always)

**Comment by qpernil** [comment]
The 2.3.0 behaviour was a pragmatic approach to mapping the YubiHSM into pkcs#11, where CKA_ID was used to represent the actual object id on the YubiHSM. This was possible since the YubiHSM allows the same object id to be used for objects of different type, such as private keys and certificates. With the old behaviour CKA_ID was always parsed into a 16 bit integer (the two first one or two bytes, depending on the length) so the length was not that important as long as the ID was present in the first bytes, and always returned as two bytes when getting CKA_ID from the YUbiHSM. Now we use metadata to make the CKA_ID handling work more like it is supposed to, preserving both value and length. I realize this could break some applications but at the same time it surprises me that XCA would behave like you describe, it seems to me that should not work with many pkcs#11 modules.

**Comment by driseley** [comment]
Thanks for the clarification, for your interest - this appears to be the problematic code in XCA:

```
pk11_attr_data pki_scard::getIdAttr() const
{
	pk11_attr_data id(CKA_ID);
	if (object_id.isEmpty())
		return id;
	BIGNUM *bn = NULL;
	BN_hex2bn(&bn, CCHAR(object_id));
	id.setBignum(bn, true);
	return id;
}
```

The CKA_ID is actually persisted as a hex string, then mapped back to the BIGNUM , which then causes it to be written back with the shortest possible encoding.  I'll try to fix this in XCA - but I don't think it's a yubihsm issue now, so many thanks for all your assistance, I'll close this now.
