### ISSUE TITLE
Problems with object IDs in yubihsm_pkcs11.so 2.4.0 (caused by Meta Object indirection)

### ISSUE THREAD

**Issue by hko-s** [Yubico/yubihsm-shell#345]
I believe there are two regressions in `yubihsm_pkcs11.so` version 2.4.0, regarding the handling of object IDs:

## No uniqueness guarantee for IDs that use Meta Object indirection

When uploading an object with a "long" ID (>2 bytes), there seems to be no mechanism that guarantees the uniqueness of the resulting `"ID, Type"` pairs. For example, it's possible to upload (`C_CreateObject`) multiple `CKO_PRIVATE_KEY` objects with the ID `[1, 1, 1]`.

The objects will get unique internal IDs, of course. However, when looking up (via `C_FindObjects`) `CKA_ID=[1, 1, 1]` and type `CKA_PRIVATE`, the PKCS#11 driver returns multiple results. This is unexpected and seems wrong to me.

## Meta Object indirection also used for one-byte IDs

Separately, the PCKS#11 driver also uses the "Meta Object" indirection for one-byte long object IDs (presumably by mistake: https://developers.yubico.com/YubiHSM2/Component_Reference/PKCS_11/#_version_2_4_0_or_later documents that only `CKA_ID` "longer than two bytes" are handled with Meta Objects).

So when uploading an object with a one-byte ID (like `[1]`), the object is assigned a synthetic two-byte internal ID.  

Combined with the first regression (above), this means that it's possible to upload multiple objects of the same type with the same one-byte ID (e.g. multiple `CKO_PRIVATE_KEY` objects with ID `[1]`).

### One-byte ID and Two-byte ID with leading zero are considered distinct objects

Additionally, unlike with `yubihsm_pkcs11.so` version 2.3.2, the current PKCS#11 driver considers ID `[0, 1]` a different object from ID `[1]` (since the latter is handled via a Meta Object indirection).

----

All of this confused me quite a bit, before I understood what is going on internally.

**Possible improvements**

I think it would be good to normalize IDs (for all read- and write-commands):

a) First strip leading zero bytes, and then
b) Make sure to handle both 1-byte IDs and 2-byte IDs as "regular" IDs (see: https://github.com/Yubico/yubihsm-shell/blob/b21923dc147daa5bb5300cd1b207daff098d3687/pkcs11/util_pkcs11.c#L4337).

Independently, I think it would be good to enforce uniqueness of "long ID"/type pairs.

**Comment by qpernil** [comment]
From http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html :

4.6.3:
"The CKA_ID attribute is intended as a means of distinguishing multiple public-key/private-key pairs held by the same subject (whether stored in the same token or not). (Since the keys are distinguished by subject name as well as identifier, it is possible that keys for different subjects may have the same CKA_ID value without introducing any ambiguity.)

It is intended in the interests of interoperability that the subject name and key identifier for a certificate will be the same as those for the corresponding public and private keys (though it is not required that all be stored in the same token). However, Cryptoki does not enforce this association, or even the uniqueness of the key identifier for a given subject; in particular, an application may leave the key identifier empty."

4.7.2:
"The CKA_ID field is intended to distinguish among multiple keys. In the case of public and private keys, this field assists in handling multiple keys held by the same subject; the key identifier for a public key and its corresponding private key should be the same. The key identifier should also be the same as for the corresponding certificate, if one exists. Cryptoki does not enforce these associations, however. (See Section 4.6 for further commentary.)

In the case of secret keys, the meaning of the CKA_ID attribute is up to the application."

Also, table 19 and table 22 specifies that CKA_ID is a byte array (of any length) that is by default empty

This indicates to me that CKA_ID does not have to be unique, per object type or otherwise, and that it is entirely up to the client application what values are stored. The only thing the spec says is that objects in the same 'group' should have the same value. One should probably think of CKA_ID as being a 'where' clause in a database search, which might give multiple results. To further distinguish one might use additional attributes, or simply let the user choose.

Given the above we now allow CKA_ID to be set to any value (up to a reasonable maximum length), and we will then return that same ID for the stored object (or in searches). I order to avoid creating metadata for all objects we still treat a 2 byte CKA_ID as an object identifier, and this also allows CKA_ID to be used to create objects with specific IDs in the device. The reason we create metadata for anything other than 2 bytes is so we can return exactly the same value as specified, which any pkcs#11 application would expect. If no metadata is stored the CKA_ID for an object is taken to be the big-endian encoding of the 16 bit object id, in other words always 2 bytes.

I realise that the previous behaviour of yubihsm_pkcs11 might make you expect uniqueness enforcement (and for two byte CKA_IDs that's still true), but as far as I can tell the current behaviour is more correct.

I hope this long-winded explanation helps.

**Comment by hko-s** [comment]
Thank you for the detailed reply! I'll take a bit of time to digest it.

If the semantics in 2.4.0 are indeed as intended, then I think it would be good to adjust the documentation at https://developers.yubico.com/YubiHSM2/Component_Reference/PKCS_11/#_version_2_4_0_or_later. It currently states:

> Meta Objects are created as needed when the function to create an object is called with CKA_ID and/or CKA_LABEL values that are longer than **2** and 40 bytes respectively

I might have been slightly less confused if that passage didn't claim that only >2 byte CKA_ID are handled in this new way.

**Comment by qpernil** [comment]
Thanks for your feedback ! I will forward the suggested documentation clarification.

**Comment by hko-s** [comment]
Again, thank you for taking the time to explain the background (and for the helpful quotes from the cryptoki standard).

I now see your points, and it seems right to me that the new behavior is indeed more correct.

I can't judge if the tradeoff to handle two-byte IDs differently from other lengths is the best tradeoff. But I understand the reasoning, and have no strong feelings about it, myself.

Either way, I assume more people will trip over the non-uniformity of the CKA_ID namespace.
So thanks for forwarding my suggestions for clarifying the documentation, I hope that more documentation (and this issue) will help future users of the pkcs11 driver.
